// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ficyicxwcshsfdbzmedx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpY3lpY3h3Y3Noc2ZkYnptZWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTg2NjUsImV4cCI6MjA2MjQ3NDY2NX0.OJkdkK7hGz2aeqohoq2QSMVMPKyXCusZ0ddZupVb-bM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);